jobs:
  build_terraform_validate:
    machine: 
      image: ubuntu-2204:2024.04.4
    steps:
      - checkout
      - run:
          name: installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      # - run: cd ./app && npm install && npm run build
      - run: 
          name: installing terraform
          command: |
            wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install terraform
      - run:
          name: validate terraform installation
          command: |
            terraform version
            cd terraform/modules
            terraform fmt
            terraform validate
  build_terragrunt_plan:
    machine:
      image: ubuntu-2204:2024.04.4
    steps:
      - attach_workspace:
         at: .
      - checkout
      - run:
          name: installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      # - run: cd ./app && npm install && npm run build
      - run: 
          name: installing terraform
          command: |
            wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install terraform
      - run:
          name: validate terraform installation
          command: |
            terraform version
      - run:
          name: installing terragrunt
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/circleci/.bashrc
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            brew install terragrunt
            sudo apt-get install build-essential
      - run:
          name: validate terragrunt installation
          command: terragrunt --version
      - run:
            name: terragrunt plan
            command: |
              cd environments/dev
              set +e
              terragrunt run-all plan > plan_output.log 2>&1
              PLAN_EXIT_CODE=$?
              set -e
              if [ $PLAN_EXIT_CODE -ne 0 ]; then
                echo "Terragrunt plan failed"
                cat plan_output.log
                exit $PLAN_EXIT_CODE
              else
                echo "Terragrunt plan succeeded"
                cat plan_output.log
              fi                     
  deploy_terragrunt:
    machine:
      image: ubuntu-2204:2024.04.4
    steps:
      - attach_workspace:
         at: .
      - checkout
      - run:
          name: installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      # - run: cd ./app && npm install && npm run build
      - run: 
          name: installing terraform
          command: |
            wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install terraform
      - run:
          name: validate terraform installation
          command: |
            terraform version
      - run:
          name: installing terragrunt
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/circleci/.bashrc
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            brew install terragrunt
            sudo apt-get install build-essential
      - run:
          name: validate terragrunt installation
          command: terragrunt --version
      - run:
            name: terragrunt deploy
            command: |
              cd environments/dev
              set +e
              terragrunt run-all apply
              PLAN_EXIT_CODE=$?
              set -e
              if [ $PLAN_EXIT_CODE -ne 0 ]; then
                echo "Terragrunt apply failed"
                exit $PLAN_EXIT_CODE
              else
                echo "Terragrunt apply succeeded"
              fi                 
              
workflows:
  version: 2
  # execute_terraform_validate:
  #   jobs:
  #     - build_terraform_validate
  #     - build_terragrunt_plan:
  #         requires:
  #           - build_terraform_validate
  terragrunt_plan:
    jobs:
      - build_terragrunt_plan
      - deploy_terragrunt:
          requires:
            - build_terragrunt_plan
