jobs:
  build_validate:
    machine: 
      image: ubuntu-2204:2024.04.4
    steps:
      - checkout
      - run:
          name: installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      # - run: cd ./app && npm install && npm run build
      - run: aws s3 ls
workflows:
  version: 2
  execute_terraform_validate:
    jobs:
      - build_validate